<?php
// FAX
//require_once 'C:\Users\AnchanFX\Workspace\Git\Accident-Report-Server\AccidentReportServer\src\Sender.php';
// GUN
//require_once 'C:\Users\gungii\git\Accident-Report-Server\AccidentReportServer\src\Sender.php';
// DEUAN
//
/**
 * Test class for Sender.
 * Generated by PHPUnit on 2014-09-09 at 23:07:46.
 */
class SenderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Sender
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sender;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Sender::Acknowledge
     * @todo Implement testAcknowledge().
     */
    public function testAcknowledge()
    {
        $this->assertEquals('ACK', $this->object->Acknowledge('ACK'));
    }
}
?>
