<?php

// FAX
require_once 'C:\Users\AnchanFX\Workspace\Git\Accident-Report-Server\AccidentReportServer\src\Time.php';

/**
 * Test class for Time.
 * Generated by PHPUnit on 2014-09-29 at 17:29:27.
 */
class TimeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Time
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Time;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Time::getThailandTime
     * @todo Implement testGetThailandTime().
     */
    public function testGetThailandTime()
    {
    	
    }
    
    public function testGetTimeStamp()
    {
    	$dateTime = '2014-09-28 16:21:51';
    	$timeStamp = $this->object->getTimeStamp($dateTime);
    	$expect = 1411921311 - 25200;
    	
    	$this->assertEquals($expect, $timeStamp);
    }
}
?>
